/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab7p2_juanflores;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.nio.Buffer;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author JD
 */
public class Principal extends javax.swing.JFrame {

    JFileChooser selecciona = new JFileChooser();
    File archivo;
    FileInputStream entrada;
    FileOutputStream salida;
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        
        
    }
    
    public String abrirArchivo(File archivo){
        String documento = "";
        
        try {
            entrada = new FileInputStream(archivo);
            int ascci;
            while((ascci=entrada.read())!=-1){
               char caracter = (char)ascci;
               documento+=caracter;
            }
            
        } catch (Exception e) {
            
        }
        return documento;
    }
    
    public String guardarArchivo(File archivo, String documento){
        String mensaje = null;
        try {
            salida = new FileOutputStream(archivo);
            byte[] sitxt = documento.getBytes();
            salida.write(sitxt);
            mensaje="archivo guardado";
        } catch (Exception e) {
            
            
            
        }
        
        return mensaje;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_marcaCarro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bt_color = new javax.swing.JButton();
        txt_modeloCarro = new javax.swing.JTextField();
        txt_año = new javax.swing.JTextField();
        txt_PrecioVenta = new javax.swing.JTextField();
        btn_agregarVehiculo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_nombreVendedor = new javax.swing.JTextField();
        btn_AgregarVendedor = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_nombreCliente = new javax.swing.JTextField();
        txt_profesionCliente = new javax.swing.JTextField();
        btn_agregarCliente = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt_sueldoDisponible = new javax.swing.JTextField();
        edadCliente = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cb_vendedor = new javax.swing.JComboBox<>();
        cb_comprador = new javax.swing.JComboBox<>();
        cb_vehiculo = new javax.swing.JComboBox<>();
        txt_CostoTransaccion = new javax.swing.JTextField();
        btn_GuardarArchivo = new javax.swing.JButton();
        btn_archivoVenta = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnabrir = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        arbolito = new javax.swing.JTree();
        MostrarArbol = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Marca");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Color");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Modelo");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Año");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Precio Venta");

        bt_color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_colorMouseClicked(evt);
            }
        });

        btn_agregarVehiculo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_agregarVehiculo.setText("Agregar Vehiculo");
        btn_agregarVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarVehiculoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(231, 231, 231)
                                .addComponent(jLabel5)))
                        .addGap(104, 104, 104)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_modeloCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_marcaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_color, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_año, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_PrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(btn_agregarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(454, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_marcaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bt_color, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_modeloCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_PrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btn_agregarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Vehiculo", jPanel1);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Nombre Vendedor");

        btn_AgregarVendedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_AgregarVendedor.setText("Agregar Vendedor");
        btn_AgregarVendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AgregarVendedorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel7)
                        .addGap(54, 54, 54)
                        .addComponent(txt_nombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(btn_AgregarVendedor)))
                .addContainerGap(468, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(169, 169, 169)
                .addComponent(btn_AgregarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Vendedor", jPanel2);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Nombre");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Edad");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Profesion ");

        btn_agregarCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_agregarCliente.setText("Agregar Cliente");
        btn_agregarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarClienteMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Sueldo Disponible");

        edadCliente.setModel(new javax.swing.SpinnerNumberModel(18, null, null, 1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel10))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_profesionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_sueldoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)))
                .addGap(459, 459, 459))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(btn_agregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(edadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_profesionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sueldoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btn_agregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("Crear Cliente", jPanel3);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Vendedor");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Comprador");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Costo Transaccion");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Vehiculo");

        cb_vendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_vendedorMouseClicked(evt);
            }
        });
        cb_vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_vendedorActionPerformed(evt);
            }
        });

        cb_comprador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_compradorMouseClicked(evt);
            }
        });

        cb_vehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_vehiculoMouseClicked(evt);
            }
        });

        btn_GuardarArchivo.setText("Guardar Archivo");
        btn_GuardarArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_GuardarArchivoMouseClicked(evt);
            }
        });

        btn_archivoVenta.setText("Crear Archivo");
        btn_archivoVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_archivoVentaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(56, 56, 56)
                                .addComponent(cb_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(57, 57, 57)
                                .addComponent(txt_CostoTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_comprador, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(btn_archivoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(btn_GuardarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(421, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cb_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cb_comprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_CostoTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(cb_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_GuardarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_archivoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        jTabbedPane1.addTab("Crear Venta", jPanel4);

        btnabrir.setText("Abrir Archivo");
        btnabrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnabrirMouseClicked(evt);
            }
        });

        btnguardar.setText("Guardar Archivo");
        btnguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnguardarMouseClicked(evt);
            }
        });
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        txtarea.setColumns(20);
        txtarea.setRows(5);
        jScrollPane1.setViewportView(txtarea);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnabrir, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162)
                        .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(398, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnabrir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Modificar Archivo JSON", jPanel5);

        jScrollPane2.setViewportView(arbolito);

        MostrarArbol.setText("Mostrar");
        MostrarArbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MostrarArbolMouseClicked(evt);
            }
        });
        MostrarArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarArbolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(MostrarArbol)
                .addGap(108, 108, 108)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(525, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(MostrarArbol)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Arbol 1", jPanel6);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setText("BASE DE DATOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_colorMouseClicked
        bt_color.setBackground(
                JColorChooser.showDialog(this, "Seleccione un color", Color.yellow));
    }//GEN-LAST:event_bt_colorMouseClicked

    private void btn_agregarVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarVehiculoMouseClicked
        
        
        
        File Archivo = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        
        try {
            Archivo = new File(".//Vehiculos.txt");
            fw = new FileWriter(Archivo,true);
            bw = new BufferedWriter(fw);
            
            bw.write("[");
            bw.newLine();
            bw.write("\t"+txt_marcaCarro.getText()+",");
            bw.newLine();
            bw.write("\t"+txt_modeloCarro.getText()+",");
            bw.newLine();
            bw.write("\t"+bt_color.getBackground().toString()+",");
            bw.newLine();
            bw.write("\t"+txt_año.getText()+",");
            bw.newLine();
            bw.write("\t"+txt_PrecioVenta.getText()+",");
            bw.newLine();
            bw.write("]");
            bw.newLine();
            
            bw.flush();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
        
        vehiculos.add(new Vehiculo(txt_marcaCarro.getText(),txt_modeloCarro.getText(),Integer.parseInt(txt_año.getText()) , Double.parseDouble(txt_PrecioVenta.getText())));
        
        JOptionPane.showMessageDialog(this, "VehiculoAgregado");
                
        txt_marcaCarro.setText("");
        txt_modeloCarro.setText("");
        txt_año.setText("");
        txt_PrecioVenta.setText("");      
    }//GEN-LAST:event_btn_agregarVehiculoMouseClicked

    private void btn_AgregarVendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AgregarVendedorMouseClicked
        File archivo = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        
        try {
            archivo = new File(".//Vendedores.txt");
            fw = new FileWriter(archivo,true);
            bw = new BufferedWriter(fw);
            
            bw.write("[");
            bw.newLine();
            bw.write("\t"+txt_nombreVendedor.getText()+",");
            bw.newLine();
            bw.write("]");
            bw.newLine();
            
            bw.flush();
            bw.close();
            fw.close();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        vendedores.add(new Vendedor(txt_nombreVendedor.getText()));
        
        JOptionPane.showMessageDialog(this, "Vendedor agregado correctamente");
        
        txt_nombreVendedor.setText("");
    }//GEN-LAST:event_btn_AgregarVendedorMouseClicked

    private void btn_agregarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarClienteMouseClicked
        File archivo = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        
        try {
            archivo = new File(".//Clientes.txt");
            fw = new FileWriter(archivo,true);
            bw = new BufferedWriter(fw);
            
            bw.write("[");
            bw.newLine();
            bw.write("\t"+txt_nombreCliente.getText()+",");
            bw.newLine();
            bw.write("\t"+edadCliente.getValue()+",");
            bw.newLine();
            bw.write("\t"+txt_profesionCliente.getText()+",");
            bw.newLine();
            bw.write("\t"+txt_sueldoDisponible.getText()+",");
            bw.newLine();
            bw.write("]");
            bw.newLine();
            
            bw.flush();
            bw.close();
            fw.close();
            
           
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        Cliente.add(new Cliente(txt_nombreCliente.getText(),Integer.parseInt(edadCliente.getValue().toString()) , txt_profesionCliente.getText(), Integer.parseInt(txt_sueldoDisponible.getText())));
        
        
        JOptionPane.showMessageDialog(this, "Cliente agregado correctamente");
        
        txt_nombreCliente.setText("");
        txt_profesionCliente.setText("");       
        txt_sueldoDisponible.setText("");
    }//GEN-LAST:event_btn_agregarClienteMouseClicked

    private void cb_vendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_vendedorMouseClicked
       cb_vendedores();
    }//GEN-LAST:event_cb_vendedorMouseClicked

    private void cb_compradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_compradorMouseClicked
     cb_clientes();
        
    }//GEN-LAST:event_cb_compradorMouseClicked

    private void cb_vehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_vehiculoMouseClicked
        cb_vehiculos();

    }//GEN-LAST:event_cb_vehiculoMouseClicked

    private void btn_archivoVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_archivoVentaMouseClicked
        File Archivo = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
     
        
            Object seleccion = cb_vendedor.getSelectedItem();             
                   
            String vendedor = seleccion.toString();
            
            Object seleccion2 = cb_comprador.getSelectedItem();
                      
            String comprador = seleccion2.toString();
            
            Object seleccionAuto = cb_vehiculo.getSelectedItem();
                      
            String AutoComprado = seleccionAuto.toString();
        
        try {
            Archivo = new File("./Ventas.txt");
            fw = new FileWriter(Archivo,true);
            bw = new BufferedWriter(fw);
            int cont = 1 ;
            
            
            
            bw.write("[");
            bw.newLine();
            bw.write("\t"+cont+",");
            bw.newLine();
            bw.write("\t"+vendedor+",");
            bw.newLine();
            bw.write("\t"+comprador+",");
            bw.newLine();
            bw.write("\t"+AutoComprado+",");
            bw.newLine();
            bw.write("]");
            bw.newLine();
            
            bw.flush();
            bw.close();
            fw.close();
            cont++;
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
        
        Venta.add(new Venta(vendedor, comprador, Integer.parseInt(txt_CostoTransaccion.getText()),AutoComprado));
        
        JOptionPane.showMessageDialog(this, "Venta realizadada");
                
        txt_CostoTransaccion.setText("");
        
    }//GEN-LAST:event_btn_archivoVentaMouseClicked

    private void cb_vendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_vendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_vendedorActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        cb_vendedores();
        cb_clientes();
        cb_vehiculos();
                
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void btnabrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnabrirMouseClicked
        
        if(selecciona.showDialog(null,"Abrir")==JFileChooser.APPROVE_OPTION){
            archivo=selecciona.getSelectedFile();
            if(archivo.canRead()){
                if(archivo.getName().endsWith("txt")){
                    String documento = abrirArchivo(archivo);
                    txtarea.setText(documento);
                    
                }else{
                    JOptionPane.showMessageDialog(this, "archivo no compatible");
                }
            }
        }
    }//GEN-LAST:event_btnabrirMouseClicked

    private void btnguardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseClicked
        
        if(selecciona.showDialog(null, "Guardar")==JFileChooser.APPROVE_OPTION){
            archivo=selecciona.getSelectedFile();
            if(archivo.getName().endsWith("txt")){
                String documento=txtarea.getText();
                String mensaje = guardarArchivo(archivo, documento);
                if(mensaje!=null){
                    JOptionPane.showMessageDialog(this, mensaje);
                }else{
                    JOptionPane.showMessageDialog(this, "archivo no compatible");
                }
            }else{
            JOptionPane.showMessageDialog(this, "guardar documento de texto");
        }
        }
    }//GEN-LAST:event_btnguardarMouseClicked

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btn_GuardarArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_GuardarArchivoMouseClicked
      
        
        
        cb_comprador.removeAllItems();
       cb_vendedor.removeAllItems();
       cb_vehiculo.removeAllItems();
             
       
       String nombre = JOptionPane.showInputDialog("Digite el nombre del archivo");
       
        try {
            
            File archivo = new File("./" + nombre + ".txt");
            FileWriter fw = new FileWriter(archivo);
            BufferedWriter bw = new BufferedWriter(fw);
            
            for (int i = 0; i < Venta.size(); i++) {
                int venta = i + 1;
                
                String vendedor = Venta.get(i).getVendedor();
                String clientecompro = Venta.get(i).getClienteCompro();
                double costoo = Venta.get(i).getCostoTransaccion();
                String carroVendido = Venta.get(i).getCarroVendido();
                
                bw.write("[");
                bw.newLine();
                bw.write("\t"+venta+",");
                bw.newLine();
                bw.write("\t"+vendedor+",");
                bw.newLine();
                bw.write("\t"+clientecompro+",");
                bw.newLine();
                bw.write("\t"+carroVendido+",");
                bw.newLine();
                bw.write("]");
                bw.newLine();
                
                bw.flush();
                bw.close();
                fw.close();
                
        }
            
        } catch (Exception e) {
            
        }
            
             
      
         
    }//GEN-LAST:event_btn_GuardarArchivoMouseClicked

    private void MostrarArbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarArbolMouseClicked
        
    }//GEN-LAST:event_MostrarArbolMouseClicked

    private void MostrarArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarArbolActionPerformed
       
    
    }//GEN-LAST:event_MostrarArbolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    private void cb_clientes(){
         DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_comprador.getModel();
        modelo.removeAllElements();
        
        
        
        
        File vendedoresAAA=null;
                
       
        
        try {
            
            vendedoresAAA= new File("./Clientes.txt");
            
            String vendedoresR = "";
            
            Scanner leer = new Scanner (vendedoresAAA);
            
            while(leer.hasNext()){
                
                vendedoresR += leer.next();
                
            }
            
            String [] vendedoArray = vendedoresR.split("]");
            
            String []token;
            
            for (int i = 0; i < vendedoArray.length; i++) {
                
                token = vendedoArray[i].split(",");
                
                for (int j = 0; j < token.length; j++) {
                    
                    if (j==0) {
                        String si = "";
                        for (int k = 1; k<token[j].length(); k++) {
                            
                            si+=token[j].charAt(k);
                        }
                        
                        modelo.addElement(si);
                       
                    }
                    
                }
                
            }
            
             leer.close();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
         
        
        cb_comprador.setModel(modelo);
          
           
    }
    private void cb_vehiculos(){
         DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_vehiculo.getModel();
        modelo.removeAllElements();
        
        
        
        
        File vendedoresAAA=null;
                
       
        
        try {
            
            vendedoresAAA= new File("./Vehiculos.txt");
            
            String vendedoresR = "";
            
            Scanner leer = new Scanner (vendedoresAAA);
            
            while(leer.hasNext()){
                
                vendedoresR += leer.next();
                
            }
            
            String [] vendedoArray = vendedoresR.split("]");
            
            String []token;
            
            for (int i = 0; i < vendedoArray.length; i++) {
                
                token = vendedoArray[i].split(",");
                
                for (int j = 0; j < token.length; j++) {
                    
                    if (j==0) {
                        String si = "";
                        for (int k = 1; k<token[j].length(); k++) {
                            
                            si+=token[j].charAt(k);
                        }
                        
                        modelo.addElement(si);
                       
                    }
                    
                }
                
            }
            
             leer.close();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
         
        
        cb_vehiculo.setModel(modelo);
          
           
    }
    
    private void cb_vendedores(){
       
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_vendedor.getModel();
        modelo.removeAllElements();
        
        
        
        
        File vendedoresAAA=null;
                
       
        
        try {
            
            vendedoresAAA= new File("./Vendedores.txt");
            
            String vendedoresR = "";
            
            Scanner leer = new Scanner (vendedoresAAA);
            
            while(leer.hasNext()){
                
                vendedoresR += leer.next();
                
            }
            
            String [] vendedoArray = vendedoresR.split("]");
            
            String []token;
            
            for (int i = 0; i < vendedoArray.length; i++) {
                
                token = vendedoArray[i].split(",");
                
                for (int j = 0; j < token.length; j++) {
                    
                    if (j==0) {
                        String si = "";
                        for (int k = 1; k<token[j].length(); k++) {
                            
                            si+=token[j].charAt(k);
                        }
                        
                        modelo.addElement(si);
                       
                    }
                    
                }
                
            }
            
             leer.close();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
         
        
        cb_vendedor.setModel(modelo);
          
           
        
    }
    
    ArrayList <Vehiculo> vehiculos = new ArrayList();
    ArrayList <Vendedor> vendedores = new ArrayList();
    ArrayList <Cliente> Cliente = new ArrayList();
    ArrayList <Venta> Venta = new ArrayList();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MostrarArbol;
    private javax.swing.JTree arbolito;
    private javax.swing.JButton bt_color;
    private javax.swing.JButton btn_AgregarVendedor;
    private javax.swing.JButton btn_GuardarArchivo;
    private javax.swing.JButton btn_agregarCliente;
    private javax.swing.JButton btn_agregarVehiculo;
    private javax.swing.JButton btn_archivoVenta;
    private javax.swing.JButton btnabrir;
    private javax.swing.JButton btnguardar;
    private javax.swing.JComboBox<String> cb_comprador;
    private javax.swing.JComboBox<String> cb_vehiculo;
    private javax.swing.JComboBox<String> cb_vendedor;
    private javax.swing.JSpinner edadCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txt_CostoTransaccion;
    private javax.swing.JTextField txt_PrecioVenta;
    private javax.swing.JTextField txt_año;
    private javax.swing.JTextField txt_marcaCarro;
    private javax.swing.JTextField txt_modeloCarro;
    private javax.swing.JTextField txt_nombreCliente;
    private javax.swing.JTextField txt_nombreVendedor;
    private javax.swing.JTextField txt_profesionCliente;
    private javax.swing.JTextField txt_sueldoDisponible;
    private javax.swing.JTextArea txtarea;
    // End of variables declaration//GEN-END:variables
}



